//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.269
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace XtremePaddle {
    using System;
    
    
    /// <summary>
    ///   Clase de recurso con establecimiento inflexible de tipos, para buscar cadenas traducidas, etc.
    /// </summary>
    // StronglyTypedResourceBuilder generó automáticamente esta clase
    // a través de una herramienta como ResGen o Visual Studio.
    // Para agregar o quitar un miembro, edite el archivo .ResX y, a continuación, vuelva a ejecutar ResGen
    // con la opción /str o vuelva a generar su proyecto de VS.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class CatStrings {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal CatStrings() {
        }
        
        /// <summary>
        ///   Devuelve la instancia de ResourceManager almacenada en caché utilizada por esta clase.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("XtremePaddle.Lenguajes.CatStrings", typeof(CatStrings).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Reemplaza la propiedad CurrentUICulture del subproceso actual para todas las
        ///   búsquedas de recursos mediante esta clase de recurso con establecimiento inflexible de tipos.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a ABOUT.
        /// </summary>
        internal static string aboutTittle {
            get {
                return ResourceManager.GetString("aboutTittle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Puck:.
        /// </summary>
        internal static string ballOptions {
            get {
                return ResourceManager.GetString("ballOptions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Classic.
        /// </summary>
        internal static string classicOptions {
            get {
                return ResourceManager.GetString("classicOptions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Coming Soon with Xbox Live.
        /// </summary>
        internal static string comingAchiev {
            get {
                return ResourceManager.GetString("comingAchiev", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Developed by:.
        /// </summary>
        internal static string developedAbout {
            get {
                return ResourceManager.GetString("developedAbout", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Difficulty:.
        /// </summary>
        internal static string difficultyOptions {
            get {
                return ResourceManager.GetString("difficultyOptions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a GAME OVER.
        /// </summary>
        internal static string gameOverTittle {
            get {
                return ResourceManager.GetString("gameOverTittle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Glow.
        /// </summary>
        internal static string glowOptions {
            get {
                return ResourceManager.GetString("glowOptions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a HIGHSCORE: .
        /// </summary>
        internal static string highScoreSurvMenu {
            get {
                return ResourceManager.GetString("highScoreSurvMenu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Paddle AI:.
        /// </summary>
        internal static string iaOptions {
            get {
                return ResourceManager.GetString("iaOptions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Info &amp; Support:.
        /// </summary>
        internal static string infoAbout {
            get {
                return ResourceManager.GetString("infoAbout", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Loading....
        /// </summary>
        internal static string loadingText {
            get {
                return ResourceManager.GetString("loadingText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a YOU LOSE.
        /// </summary>
        internal static string loseText {
            get {
                return ResourceManager.GetString("loseText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Music:.
        /// </summary>
        internal static string musicAbout {
            get {
                return ResourceManager.GetString("musicAbout", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a OPTIONS 1P.
        /// </summary>
        internal static string options1Tittle {
            get {
                return ResourceManager.GetString("options1Tittle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a OPTIONS 2P.
        /// </summary>
        internal static string options2Tittle {
            get {
                return ResourceManager.GetString("options2Tittle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a PAUSED.
        /// </summary>
        internal static string pausedTittle {
            get {
                return ResourceManager.GetString("pausedTittle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Paddle J2:.
        /// </summary>
        internal static string player2Options {
            get {
                return ResourceManager.GetString("player2Options", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Paddle J1:.
        /// </summary>
        internal static string playerOptions {
            get {
                return ResourceManager.GetString("playerOptions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a PLAY.
        /// </summary>
        internal static string playOptions {
            get {
                return ResourceManager.GetString("playOptions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Quit.
        /// </summary>
        internal static string quitMenu {
            get {
                return ResourceManager.GetString("quitMenu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Quit.
        /// </summary>
        internal static string quitWinMenu {
            get {
                return ResourceManager.GetString("quitWinMenu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Restart.
        /// </summary>
        internal static string restartWinMenu {
            get {
                return ResourceManager.GetString("restartWinMenu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Resume.
        /// </summary>
        internal static string resumeMenu {
            get {
                return ResourceManager.GetString("resumeMenu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a SCORE: .
        /// </summary>
        internal static string scoreSurvMenu {
            get {
                return ResourceManager.GetString("scoreSurvMenu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Xtreme Paddle is a nice and funny game..
        /// </summary>
        internal static string ShareMessage {
            get {
                return ResourceManager.GetString("ShareMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Share Xtreme Paddle.
        /// </summary>
        internal static string ShareTittle {
            get {
                return ResourceManager.GetString("ShareTittle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Sketch.
        /// </summary>
        internal static string sketchOptions {
            get {
                return ResourceManager.GetString("sketchOptions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Soccer.
        /// </summary>
        internal static string soccerOptions {
            get {
                return ResourceManager.GetString("soccerOptions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Tennis.
        /// </summary>
        internal static string tennisOptions {
            get {
                return ResourceManager.GetString("tennisOptions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Thanks to:.
        /// </summary>
        internal static string thanksAbout {
            get {
                return ResourceManager.GetString("thanksAbout", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Theme: .
        /// </summary>
        internal static string themeOptions {
            get {
                return ResourceManager.GetString("themeOptions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Version 1.5.
        /// </summary>
        internal static string versionAbout {
            get {
                return ResourceManager.GetString("versionAbout", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a YOU WIN.
        /// </summary>
        internal static string winText {
            get {
                return ResourceManager.GetString("winText", resourceCulture);
            }
        }
    }
}
